name: Go

on: [workflow_dispatch]

jobs:

  build:
    name: Build
    runs-on: windows-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Install goversioninfo
      run: go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo

    - name: Build
      shell: cmd
      run: build.bat

    - name: Upload Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: 'WinCryptSSHAgent*.exe'
        draft: true
        prerelease: true
